### ISSUE TITLE
show cennznet address of metamask wallet

### ISSUE THREAD

**Issue by holygits** [cennznet/uncover-frontend#11]
Provide an input/converter to show a cennznet address given an ethereum address

```js
function cvmToAddress(evmAddress) {
  var message = utils.stringToU8a('cvm:');
  message = utils.u8aConcat(message, new Array(7).fill(0), utils.hexToU8a(evmAddress));
  let checkSum = message.reduce((a, b) => a ^ b, 0);
  message = utils.u8aConcat(message, new Array(1).fill(checkSum));

  return utilCrypto.encodeAddress(message, 42);
}
```

**Comment by ken-centrality** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Explore and plan for better EVM support on UNCover](https://trello.com/c/cew1VTcp/12-explore-and-plan-for-better-evm-support-on-uncover)

**Comment by ken-centrality** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update UI to handle EVM address](https://trello.com/c/sV067PQH/33-update-ui-to-handle-evm-address)

**Comment by KarishmaBothara** [comment]
deployed on Rata.. will deploy on Nikau/Azalea on next Thurs and close this
