### ISSUE TITLE
EVM transactions don't appear under extrinsics tab

### ISSUE THREAD

**Issue by holygits** [cennznet/uncover-frontend#17]
balance transfer: https://nikau.uncoverexplorer.com/extrinsic/2935725-1
contract deploy: https://nikau.uncoverexplorer.com/extrinsic/2935753-1

**Comment by ken-centrality** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Explore and plan for better EVM support](https://trello.com/c/cew1VTcp/12-explore-and-plan-for-better-evm-support)

**Comment by ken-centrality** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update UNCover Scanner to accept all EVM Executed transaction as signed](https://trello.com/c/5QKJ8NTc/30-update-uncover-scanner-to-accept-all-evm-executed-transaction-as-signed)

**Comment by KarishmaBothara** [comment]
deployed on Nikau & Rata.. will deploy on Azalea on next Thurs and close this
