### ISSUE TITLE
EVM executed event ambiguous fields

### ISSUE THREAD

**Issue by holygits** [cennznet/uncover-frontend#18]
The fields aren't named here (H160, H160, 256) so it's hard to decipher
<img width="1214" alt="Screen Shot 2022-04-28 at 13 35 27" src="https://user-images.githubusercontent.com/5133901/165658764-75142a97-d3ac-41fc-803f-efb68c959477.png">

**Comment by ken-centrality** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Explore and plan for better EVM support](https://trello.com/c/cew1VTcp/12-explore-and-plan-for-better-evm-support)

**Comment by ken-centrality** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update UI to handle ambiguous fields from EVM tx](https://trello.com/c/RpEuxaqx/32-update-ui-to-handle-ambiguous-fields-from-evm-tx)

**Comment by KarishmaBothara** [comment]
deployed on Rata.. will deploy on Azalea/Nikau on next Thurs and close this
