### ISSUE TITLE
EVM balance transfers

### ISSUE THREAD

**Issue by holygits** [cennznet/uncover-frontend#25]
evm and erc20 balance transfers should be scanned and appropriate GA balances updated

**Comment by ken-centrality** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Explore and plan for better EVM support](https://trello.com/c/cew1VTcp/12-explore-and-plan-for-better-evm-support)

**Comment by ken-centrality** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make CPAY Transfers appear correctly](https://trello.com/c/rTMVg2UL/31-make-cpay-transfers-appear-correctly)

**Comment by KarishmaBothara** [comment]
Native GA transfers are available.. CPAY transfer via EVM is done.. deployed on rata/nikau/
Will go on Azalea next Thursday..  for ERC20 balance transfer, need to save the contact source to decode the data
